# Generated by Django 3.0.8 on 2020-07-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='short',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='technology1',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='technology2',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='technology3',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(default='default', path='/img'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
