# Generated by Django 3.0.8 on 2020-07-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200725_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='default'),
        ),
        migrations.AddField(
            model_name='project',
            name='link_text',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
