# Generated by Django 3.0.8 on 2020-07-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_exp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FilePathField(default='default', path='/img')),
                ('title', models.CharField(default='default', max_length=20)),
            ],
        ),
    ]
